function tao = open_controller(robot, t, y, Td, veld, accd, dt)
n = robot.dof;
cnt = round(t / dt) + 1;
q = y(1:n);
qd = y(n + 1 : 2 * n);
[dJb, Jb] = derivative_jacobian_matrix(robot, q, qd);
invJb = pinv(Jb);
[M, C, G] = mass_c_g_matrix(robot, q, qd);
Rd = Td(1:3, 1:3, cnt);
wd = Rd' * veld(1:3, cnt);
vd = Rd' * veld(4:6, cnt);
Vd = [wd;vd];
alphad = Rd' * accd(1:3, cnt);
ad = Rd' * accd(4:6, cnt);
dVd = [alphad;ad - cross(wd, vd)];
tao = G + M * invJb * dVd + (C * invJb - M * invJb * dJb * invJb) * Vd;
