rigid_body = importrobot('urdf\IP\urdf\IP.urdf');
rigid_body.DataFormat = 'column';
rigid_body.Gravity = [0 -9.81 0];
robot = get_robot_chain(rigid_body, 'rod','base_link');
robot.gravity = [0 -9.81 0];
m = 1;
M = 1;
l = 0.5;
g = 9.8;
A = [0, 0, 1, 0; 
     0, 0, 0, 1; 
     0, 3 * m * g / (4 * M + m), 0, 0;
     0, 6 * (M + m) * g / (l * (4 * M + m)), 0, 0];
B = [0;0;4/ (4 * M + m); 6 / (l * (4 * M + m))];
C = [1, 0, 0, 0];
D = 0;
init_pos = [0, 0];
p = cal_second_order_pole(0.0001, 1);
p = [4 * real(p(1)), 3.5 * real(p(1)), p];
K = place(A, B, p);
%% 极点配置
% L = place(A', C', p)';
kf = -1 / (C*((A - B*K) \ B));
Q = 1e-2;
R = 1e-4;
Ts = 1e-2;
plant = ss(A, B, C, D);
d_plant = c2d(plant, Ts);