rigid_body = importrobot('urdf\IP\urdf\IP.urdf');
rigid_body.DataFormat = 'column';
rigid_body.Gravity = [0 -9.81 0];
robot = get_robot_chain(rigid_body, 'rod','base_link');
robot.gravity = [0 -9.81 0];
m = 1;
M = 1;
l = 0.5;
g = 9.8;
A = [0, 0, 1, 0; 
     0, 0, 0, 1; 
     0, 3 * m * g / (4 * M + m), 0, 0;
     0, 6 * (M + m) * g / (l * (4 * M + m)), 0, 0];
B = [0;0;4/ (4 * M + m); 6 / (l * (4 * M + m))];
C = [1, 0, 0, 0];
D = 0;
init_pos = [0, 0];
p = cal_second_order_pole(0.01, 1);
p = [4 * real(p(1)), 3.5 * real(p(1)), p];
K = place(A, B, p);
% K = lqr(A, B, 100 * eye(4), 1);
kf = -1 / (C*((A - B*K) \ B));
ki = -0.2;
A_tilde = [A - B * K, B * ki; -C, 0];
B_tilde = [B * kf, B; 1, 0];
C_tilde = [C, 0];
closed_sys = ss(A_tilde, B_tilde, C_tilde, 0);
step(closed_sys, 10);
v = 0.1;