function yd = manipulator_dynamics(robot, tao, F_ME, t, y)
n = robot.dof;
yd = zeros(2*n,1);
q = y(1:n);
qd = y(n + 1 : end);
Jb = jacobian_matrix(robot, q);
hqqd = gravity_velocity_torque(robot, q, qd);
yd(1:n) = qd;
yd(n + 1 : end) = tao(t, y) - hqqd - Jb' * F_ME(t, y);